### ISSUE TITLE
Deploying REST extensions fails with "basic" security

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/roxy#208]
When the target HTTP app server's authentication is set to "basic", the deploy modules command will fail when trying to deploy REST extensions. Contents of the source directory are deployed successfully. 

The error message:

```
Loading REST extensions from /Users/dcassel/tmp/richard/rl-test/rest-api/ext

getting files for /Users/dcassel/tmp/richard/rl-test/rest-api/ext
params: ["method=get", "method=put", "method=post", "method=delete"]
extensionName: test
loading: /Users/dcassel/tmp/richard/rl-test/rest-api/ext/test.xqy
url: http://localhost:9140/v1/config/resources/test?method=get&method=put&method=post&method=delete
Roxy::Http : request failure count: 1, exception: #<TypeError: no implicit conversion of nil into String>
Roxy::Http : request failure count: 2, exception: #<TypeError: no implicit conversion of nil into String>
Roxy::Http : request failure count: 3, exception: #<TypeError: no implicit conversion of nil into String>
Roxy::Http : request failure count: 4, exception: #<TypeError: no implicit conversion of nil into String>
Roxy::Http : re-raising same error: localhost temporarily unavailable: (no implicit conversion of nil into String) -- error count: 4, error age: 0
ERROR: localhost temporarily unavailable: (no implicit conversion of nil into String)
ERROR: ["/Users/dcassel/tmp/richard/rl-test/deploy/lib/RoxyHttp.rb:345:in `block in request'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/RoxyHttp.rb:335:in `loop'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/RoxyHttp.rb:335:in `request'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/MLClient.rb:93:in `go'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/ml_rest.rb:78:in `block in install_extensions'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/ml_rest.rb:39:in `each'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/ml_rest.rb:39:in `each_with_index'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/ml_rest.rb:39:in `install_extensions'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/server_config.rb:888:in `deploy_modules'", "/Users/dcassel/tmp/richard/rl-test/deploy/lib/server_config.rb:446:in `deploy'", "deploy/lib/ml.rb:128:in `<main>'"]
dcassel@MacPro-2396: rl-test/ $ 
```

**Comment by silviarausanu** [comment]
The problem still seems to reproduce using version 1.7.1. 
I'm using a hybrid application, authentication: basic + external ldap. What I'm getting when I execute 
<code><pre>./ml local deploy modules -v</pre></code>
<code><pre>Loaded 107 documents from /home/silvia/eaml/kbb/src to 127.0.0.1:8051/kbb-modules at 01/28/2015 04:42:01 pm</pre></code>
<code><pre>.[PUT]	http://1127.0.0.1:8050/v1/config/properties</pre></code>
<code><pre>.ERROR: Invalid login credentials for integration environment!!</pre></code>

**Comment by grtjn** [comment]
Make sure you have this in your properties:

    authentication-method=basic

Next to this, internal security needs to be true for some reason. It is almost as if you either need to use ldap or internal auth, but can't use both despite what the docs tell us..

**Comment by silviarausanu** [comment]
I have specified the authentication-method as basic, but unfortunately, I'm using internal-security = false, and have an ldap connected. 
So you're saying that in this case (external security + ldap) I should use applicationLevel authentication method (which indeed works for me at the deployment part, but causes me different problems) ?

Thank you!

**Comment by grtjn** [comment]
No, I meant that according the docs you should be able to use internal-security=true, and still be able to do both internal auth + external auth if the user was not found internally. But this doesn't work.

Roxy uses ml.user/ml.password for bootstrap, deploy, etc. That needs to be an ML internal user. But if you try to deploy REST options/extensions against an app server that uses external ldap security, that same ml.user user probably doesn't exist in your LDAP directory, and doing PUT/POST to install extensions won't work.

You can either switch back and forth the internal security while doing deploy rest, or you need to enter an LDAP user as ml.user, and recreate that user in ML so that bootstrap works with it too.

**Comment by grtjn** [comment]
Regarding switching back and forth of internal security, I am using this in app_specific.rb:

```Ruby
  # adjust REST security to allow deploy
  alias_method :original_deploy_rest, :deploy_rest
  def deploy_rest()
    r = execute_query %Q{
      xquery version "1.0-ml"; 
      
      import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
      
      let $config := admin:get-configuration()
      let $config := admin:appserver-set-internal-security($config, xdmp:server("#{@properties["ml.app-name"]}"), fn:true())
      return
        admin:save-configuration-without-restart($config)
    },
    { :app_name => @properties["ml.app-name"] }

    original_deploy_rest

    r = execute_query %Q{
      xquery version "1.0-ml"; 
      
      import module namespace admin = "http://marklogic.com/xdmp/admin" at "/MarkLogic/admin.xqy";
      
      let $config := admin:get-configuration()
      let $config := admin:appserver-set-internal-security($config, xdmp:server("#{@properties["ml.app-name"]}"), fn:false())
      return
        admin:save-configuration-without-restart($config)
    },
    { :app_name => @properties["ml.app-name"] }
  end
```

**Comment by istvannagy** [comment]
@grtjn, thanks for your reply. The proposed solution is working fine
