### ISSUE TITLE
rest options are not deployed to the test modules database

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/roxy#531]
I'm defining a test-content and test-modules database. When I deploy modules all content from src will be deployed to the test-modules database, but the rest extensions and the rest options are not deployed to the test-modules database. I do have a standard rest api on the test-port but I'm not able to utilize the rest extensions and options on the test-port.
Is that by design? Can they be added?

**Comment by grtjn** [comment]
Sounds like a bug/accidental omission to me..

**Comment by dmcassel** [comment]
Yeah, that sounds like a bug, based on unit testing being focused on MVC apps (originally). Should just need to update the deploy_modules function.

**Comment by grtjn** [comment]
Same issue also applies to rest-modules

**Comment by grtjn** [comment]
Pushing away..

**Comment by RobertSzkutak** [comment]
Fixed in dev
