### ISSUE TITLE
Define environment specific assets in ml-config.xml

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/roxy#692]
Request from a customer : 

Have an optional attribute in Roxy assets which defines environments that are allowed to use that asset.

ex:

This asset would only be deployed/wiped on dev environment:

    <role @environment='dev'/>

This asset would only be deployed/wiped on local and dev environment:

    <user @environment='local,dev'>

While you can do this with using a different ml-config,xml for each environment, it would be much more condensed to manage assets like this within a single ml-config.xml file.

**Comment by dmcassel** [comment]
I'm curious about the use case here, as a major purpose to having the
Deployer is to ensure consistency across environments. That said, I don't
see any problem supporting the feature, while keeping the default behavior.

**Comment by RobertSzkutak** [comment]
The use case described to me by the customer was that they run their testing in lower environments. And that testing needs additional users defined for automating their testing scenarios. Another use case was that they want to go through a process of promoting indexes up into higher environments and that this would be a good way to manage that for them.

**Comment by dmcassel** [comment]
Sounds good to me.

**Comment by grtjn** [comment]
I'm playing around with #808, and starting to think I need something similar. I'd like to get rid of the xml placeholders like `@ml.ssl-certificate-xml`. Instead I'd prefer doing something like:

```
      <certificate xmlns="http://marklogic.com/xdmp/pki" if-exists="@ml.ssl-certificate-template">
        <name>@ml.ssl-certificate-template</name>
        <countryName>@ml.ssl-certificate-countryName</countryName>
        <stateOrProvinceName>@ml.ssl-certificate-stateOrProvinceName</stateOrProvinceName>
        <localityName>@ml.ssl-certificate-localityName</localityName>
        <organizationName>@ml.ssl-certificate-organizationName</organizationName>
        <organizationalUnitName>@ml.ssl-certificate-organizationalUnitName</organizationalUnitName>
        <emailAddress>@ml.ssl-certificate-emailAddress</emailAddress>
      </certificate>
```
Note: the property placeholder gets replaced as anywhere else, and results in either an empty if-exists attribute, or one with a value.

Similarly we could do something like:

```
      <role if-equal="${environment}=dev"/>
```

Or maybe just `if`, and then allow `=` as well as `!=`. No eval, just tokenize, and string-compare left and right operand according to operator..

**Comment by grtjn** [comment]
I was hoping to be able to use more complex if expressions, like `property EQ "my val" AND other_property NE "other val"`, but you'd need a good parser to process that. `cts:parse` would be a great tool to use, but unfortunately not supported by MarkLogic 7. Will be difficult to 'poly-fill' that. Could try though..

**Comment by RobertSzkutak** [comment]
I'm ok with saying this feature is not ML7 supported :)

**Comment by grtjn** [comment]
Well, I had something in mind for #808, but that would affect ML7 support too. I might have found a way though. search:parse works too. Less strong, but it works. And there are some quirks with cts:parse, making search:parse do a little better actually..

Let me see if I can put a PR together for this..

**Comment by RobertSzkutak** [comment]
Implemented in DEV
