### ISSUE TITLE
Use / in triggers-config.sample.xml

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/roxy#725]
The triggers sample xml uses `/triggers/` as modules-root, causing confusion among users when imports are not found, due to unfamiliarity with what modules-root does. I'd recommend using / as modules-root, and the full path to the .xqy in the triggers sample file..

**Comment by grtjn** [comment]
Note: this ticket is not related to issue 735, nor to PR 771..

**Comment by RobertSzkutak** [comment]
Fixed in dev
