### ISSUE TITLE
Returning exit status for unit test invocation

### ISSUE THREAD

**Issue by ezbc** [marklogic-community/roxy#757]
#### Exit status always 0 for unit tests

Currently running unit tests from the terminal only prints the test results to the terminal [source link](https://github.com/marklogic/roxy/blob/0cd9666ae7e18de47da802c5bed02e077143891b/deploy/lib/server_config.rb#L1044). If there are any failing unit tests, the user needs to examine the printed xml for any errors. The exit status will always remain 0 (succeeded).

For example running

``` bash
./ml local test
```
will only return an exit status of 0 despite whether a unit test failed or not.

#### Use case

Returning an exit status for the unit tests would be valuable to automated builds of a project so that a build will fail a unit test fails.

#### Potential solution

One potential way to return the exit status based on the success of unit tests would be to parse the XML output from the test script, /test/default.xqy, and check if the "errors" or "failures" attributes in the testsuite element is anything but 0. 

I plan on writing a solution for my local project. Let me know if you would like me to submit a pull request.

**Comment by grtjn** [comment]
We'd welcome a PR. There are instructions on how to [Contribute to Roxy](https://github.com/marklogic/roxy/blob/master/CONTRIBUTING.md).

**Comment by ezbc** [comment]
Thanks for supporting this @grtjn. Apologies for not providing a PR!

**Comment by RobertSzkutak** [comment]
Fixed in dev
