### ISSUE TITLE
Internal forest replica layout is incorrect.

### ISSUE THREAD

**Issue by jamsilvia** [marklogic-community/roxy#779]
When performing a bootstrap with --replicate-internals, and more than 2 hosts in the cluster, all replicas get placed on node 2.  As of 1.7.5, Roxy should lay out the internal replicas striped across the cluster.

This can be reproduced by starting with a clean 3-node cluster and doing a ml boostrap --replicate-internals.

Linux RHEL 6 and Centos 6
MarkLogic 8
Roxy 1.7.5

**Comment by jamsilvia** [comment]
The fix for #616 was messed up when I merged it in - but the problem was not caught when delivered.  There is a map in setup.xqy, $internal-forests, that is only initialized with a counter.  This map should contain (as keys) the set of internal forest names. 
```
declare variable $internal-forests := 
  map:map() !
    ( 
      map:put( ., "internal-forest-adjust", 0 ),
      .
    );
```
This map is used to determine the internal forests and lay them out striped in "reassign-replicas":
```
let $adjuster as xs:int :=
        if( $is-internal ) then
          let $return := map:get( $internal-forests, "internal-forest-adjust" )
          return
          (
            map:put( $internal-forests, "internal-forest-adjust", $return + $num-forced-replicas ),
            $return
          )
        else 0
```

**Comment by grtjn** [comment]
Cannot reproduce with dev and MarkLogic 9.0-1.1:

<img width="902" alt="screen shot 2017-06-01 at 5 19 14 pm" src="https://cloud.githubusercontent.com/assets/611397/26686852/86d454be-46ee-11e7-8866-cb82a14398d9.png">

Other around that could run a test?

**Comment by grtjn** [comment]
Don't forget to use the --nr-replicas param: `./ml local bootstrap --replicate-internals --nr-replicas=2`

**Comment by grtjn** [comment]
@jamsilvia I was notified about a comment with more details, but you removed it?

**Comment by jamsilvia** [comment]
I did - I was trying to recall how I fixed this issue with a project we are using the feature on.  So I guessed off the top of my head, looked at the github code, couldn't determine that I was 100% correct, and thus removed it.
I plan to take a look at what we fixed with my other project this evening and see if I can recall how it all came together.

**Comment by jamsilvia** [comment]
This appeared in a project merged version of Roxy, but I do not believe it to be a problem in a "gold" version of roxy.  Closing the ticket as not reproducible.
