### ISSUE TITLE
ENV property overrides don't allow . and -

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/roxy#794]
Functionality was added that allows using command-line arguments like `--ml.xquery.dir=other-src/`. That allows overriding any known property from command-line.

Similar support was added for ENV variables. One can override the `user` property by specifying a `ml_user` ENV variable, try for instance `ml_user=xxx ./ml local info`.

Unfortunately, this does not allow specifying overrides for any property that has . or - in it, or any other character not allowed in ENV variable names. According to [this](https://stackoverflow.com/a/2821183/918496), it essentially comes down to letters, digits (not at start), and underscores.

**Comment by grtjn** [comment]
It would work if unsupported chars would be replaced by _. E.g. you'd define ENV var `ml_rest_ext_dir` if you'd want to override the property `rest-ext.dir`.

**Comment by grtjn** [comment]
Fun note, no need to worry about lower/upper case on windows..

**Comment by RobertSzkutak** [comment]
Fixed in DEV...
