### ISSUE TITLE
Roxy no longer supports server-version < 7 since v1.7.1

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/roxy#800]
Show a deprecation warning if someone uses server-version < 7, and print a reference to https://github.com/marklogic/roxy/wiki/Supported-MarkLogic-versions. We should add a list of latest Roxy release to work with each of the no-longer-supported versions to that wiki page..

**Comment by grtjn** [comment]
Also prevent people from upgrading to latest, if server-version < 7, with printing ref to same wiki page.

**Comment by grtjn** [comment]
I think we need stronger language. We still allow selecting server-version 5 and 6, but Roxy actually stopped working against those since v1.7.1. I ran a few tests for that, and made changes to https://github.com/marklogic/roxy/wiki/Supported-MarkLogic-versions accordingly..

**Comment by RobertSzkutak** [comment]
Sounds like we also need to go through and remove properties, functions and tests referencing these older versions

**Comment by grtjn** [comment]
Warning is printed as part of PR #769, which also removes version options < 7 from shown options. I'm reluctant to bluntly refuse, maybe in later release..

**Comment by grtjn** [comment]
Let's limit to warnings, and guidance for now, and hold off on severe cleanup till a later release..

**Comment by RobertSzkutak** [comment]
I think thats the way to go. I dont know to what extent older versions dont work. Perhaps some operations are ok.

**Comment by RobertSzkutak** [comment]
Fixed in dev
