### ISSUE TITLE
Bootstrap fails, setup.xqy no longer handles special characters in [env].properties files

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic-community/roxy#831]
#### The issue

Short description of the problem:
deploy/lib/setup.xqy has a syntax error at line 6369 and will not run.

What are the steps to reproduce the problem?
1. do a bootstrap or anything else that runs setup.xqy

#### Tech Specs

Which Operating System are you using?
All

Which version of MarkLogic are you using?
9.0-2

Which version of Roxy are you using (see version.txt)?
1.7.7

**Comment by grtjn** [comment]
@tdiepenbrock I see you changed the title. What kind of special chars are you talking about? I can imagine special chars could break ml-config.xml when appended to setup.xqy. There were changes related to this.

**Comment by tdiepenbrock** [comment]
Hi Geert,

I not only changed the title but also the full description.  Originally I though the issue was with setup.xqy, and it is—but only in the form that eventually gets eval’d by the server.  Properties with special characters are not being escaped for XQuery, so characters like ‘{‘ in property values completely break it.  This frequently happens with the randomly-generated app user password, for example.  We also send small hunks of JSON as property values, which also break it.

The steps to reproduce show how it breaks with the random password that Roxy generated for the app-user.

I also found a fix: the issue is actually in ServerConfig.properties_map() in server_config.rb.  This fixes it (change in bold):

  def properties_map
    entries = []
    @properties.each do |k, v|
      entries.push %Q{map:entry("#{k}", "#{v.xquery_safe}")}
    end
    "map:new((\n" + entries.join(",\n  ")+ "))"
  end

Thanks,

Tom


Thomas Diepenbrock
Technical Manager
MarkLogic Corporation
Thomas.Diepenbrock@marklogic.com<mailto:Thomas.Diepenbrock@marklogic.com>
Cell:  +1 703 980 1248

[cid:0B48B25A-8630-42FD-BFB9-3092CB213523] <http://www.marklogic.com/social/>
<http://www.marklogic.com/social/>

On Aug 16, 2017, at 1:20 AM, Geert <notifications@github.com<mailto:notifications@github.com>> wrote:


@tdiepenbrock<https://github.com/tdiepenbrock> I see you changed the title. What kind of special chars are you talking about? I can imagine special chars could break ml-config.xml when appended to setup.xqy. There were changes related to this.

**Comment by grtjn** [comment]
Looks like your description edits don't show up, so thanks for the extra detail. I'll try to take a closer look at this, since I likely touched the code that caused this..

**Comment by grtjn** [comment]
Oh, and the bold doesn't show up on github.. :)

**Comment by tdiepenbrock** [comment]
lol—just need to append “.xquery_safe” to the values in that function.

td


Thomas Diepenbrock
Technical Manager
MarkLogic Corporation
Thomas.Diepenbrock@marklogic.com<mailto:Thomas.Diepenbrock@marklogic.com>
Cell:  +1 703 980 1248

[cid:0B48B25A-8630-42FD-BFB9-3092CB213523] <http://www.marklogic.com/social/>
<http://www.marklogic.com/social/>

On Aug 16, 2017, at 3:26 PM, Geert <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, and the bold doesn't show up on github.. :)

**Comment by grtjn** [comment]
Our internal Jenkins was down unfortunately. Now that it is back up, it confirms issues with bootstrap. I suspect it succeeds or fails depending on generated appuser-password..

**Comment by tdiepenbrock** [comment]
It is not calling .xquery_safe on the values when it creates the properties map.  So any property with special characters may result in either invalid xquery or invalid entity references, etc.

td


Thomas Diepenbrock
Technical Manager
MarkLogic Corporation
Thomas.Diepenbrock@marklogic.com<mailto:Thomas.Diepenbrock@marklogic.com>
Cell:  +1 703 980 1248

[cid:0B48B25A-8630-42FD-BFB9-3092CB213523] <http://www.marklogic.com/social/>
<http://www.marklogic.com/social/>

On Aug 18, 2017, at 7:30 AM, Geert <notifications@github.com<mailto:notifications@github.com>> wrote:


Our internal Jenkins was down unfortunately. Now that it is back up, it confirms issues with bootstrap. I suspect it succeeds or fails depending on generated appuser-password..

**Comment by grtjn** [comment]
Fixed in dev

**Comment by grtjn** [comment]
A hotfix was also applied to master..
