### ISSUE TITLE
Deploying Source on app-type=bare also deploys the app directory

### ISSUE THREAD

**Issue by alan-johnson** [marklogic-community/roxy#836]
#### The issue

When the the app-type=bare, running "ml <env> deploy modules" or "ml <env> deploy src" throws an error that Roxy can't find app/config/config.xqy in the "src" directory. After adding that file in the required path, it also gets deployed to the modules database. When app-type=bare, it shouldn't throw an error if the app/config/config.xqy is missing since it is not a requirement for the deployment.

What are the steps to reproduce the problem?
1. Create a project with app-type=bare as a build.property
2. Make sure src has a file or two but no "app" directory
3. Run "ml <env> deploy modules"

#### Tech Specs

Which Operating System are you using?
Mac OSX Sierra, 10.12

Which version of MarkLogic are you using?
Version 9.0.1 and Version 8.0.5

Which version of Roxy are you using (see version.txt)?
"July-2017"

**Comment by grtjn** [comment]
Yeah, makes sense. It should probably flush the value of the config property at ml new/init for app-type bare. And it shouldn't error out, but rather warn that the app config is missing. I've seen this cause issues at upgrades too..

**Comment by grtjn** [comment]
Fixed in dev
