### ISSUE TITLE
Question: set multiple extensions for mime type?

### ISSUE THREAD

**Issue by alan-johnson** [marklogic-community/roxy#837]
## Thank you for submitting an issue!

In my ml-config.xml file, I'm trying to set multiple extensions for a mimetype. The mimetype of "video/mp4" already has 2 extensions after installing MarkLogic. I need to also add the extension of "mp4". When I set my mimetype to that extension, it replaces the original values. When I try to add multiple extensions in a comma-separated list, Roxy complains it's not a valid file extension.

Any thoughts?

**Comment by grtjn** [comment]
Use a space-separated list instead. The Admin UI shows commas, but in ml-config.xml one needs to use spaces to separate values.

**Comment by grtjn** [comment]
The example mimetype in ml-config.xml shows this by the way, it speaks of `<extension>crazy stuff</extension>`. Bootstrapping that will show `crazy,stuff` as extensions in the Admin UI..

**Comment by alan-johnson** [comment]
Thanks much, Geert. I didn't get that connection.
