### ISSUE TITLE
path fields - bootstrap broken in 8.0-7

### ISSUE THREAD

**Issue by joecrean** [marklogic-community/roxy#850]
#### 

Short description of the problem:

Since the upgrade to MarkLogic 8.0-7 roxy bootstrap fails in an environment where the application was already deployed (and by converse it does not fail in a fresh environment).
Path namespaces are removed and then added every time bootstrap runs. In order to remove them we first need to check if they are being used. They can be used in Path Range Index definitions, elements containing Geospatial co-ordinates and Field definitions. The API used to delete the path namespaces is called admin:database-delete-path-namespace. This API will check to see if the namespaces are in use before deletion and in 8.0-7 this has been tightened up to additionally check field definitions. If there are field definitions present with paths the deletion will fail with the exception ADMIN-PATHNAMESPACEINUSE. 

What are the steps to reproduce the problem?
1. Create a field with a path and path namespace definition
2. bootstrap (this will succeed)
3. bootstrap again (this will fail)

#### Tech Specs

Which Operating System are you using? CentOS 7

Which version of MarkLogic are you using? 8.0-7

Which version of Roxy are you using (see version.txt)? 1.7.6

**Comment by joecrean** [comment]
Folks, i have already created a fix for this locally and am happy to submit this in a PR. If so please let me know how you want it.. (i assume create a new branch off master and create the PR from that).. just in case you have any specific procedures.. just let me know

**Comment by dmcassel** [comment]
Hi @joecrean. We've got a [CONTRIBUTING.md](https://github.com/marklogic-community/roxy/blob/master/CONTRIBUTING.md) file that shows how to submit a PR for this project. Part of it is using a feature branch off the dev branch, rather than master. Your PR would be welcome.

**Comment by joecrean** [comment]
created pull request for this

**Comment by heelix** [comment]
If possible, we could really use this fix.  We've been waiting for it to get merged in before deploying it.

**Comment by heelix** [comment]
Did this fix actually get merged in?

**Comment by grtjn** [comment]
Unfortunately not, let me see if I can finish reviewing this. I need to take a close look at the changes..

**Comment by grtjn** [comment]
Fixed in dev
