### ISSUE TITLE
Enable trace events from ml-config file

### ISSUE THREAD

**Issue by emime93** [marklogic-community/roxy#851]
#### The issue

Trace events can not be enabled through Roxy, only trace-events-activated feature can be enabled.
Enabling the trace events through the Admin Interface in the Diagnosis section of the group is the only option currently the user has, therefore it would be nice and practical if the trace events could be added/enabled through Roxy.

#### Tech Specs

I am using Ubuntu 16.04 LTS as a OS and ML 9.0-1.1 and Roxy 1.7.7.

I have found a version (1.7.3) of Roxy here https://github.com/rlouapre/roxy, which has support for adding trace events, maybe this will be helpful.

**Comment by grtjn** [comment]
Covered by PR #842, which is ready to be merged into dev..

**Comment by grtjn** [comment]
Fixed in dev
