### ISSUE TITLE
Output of SJS Unit Tests not reported correctly in UI

### ISSUE THREAD

**Issue by tternquist** [marklogic-community/roxy#854]
CC @dmcassel 
#### The issue
Short description of the problem:
When using SJS unit tests the outputs do not appear to be correctly reported. Instead of a count, the output for tests run, passed and failed are each "-" 

What are the steps to reproduce the problem?
Can reproduce with these contents as a test file under any test suite:
```
const test = require("/test/test-helper.xqy");

(function testOne() {
    var actual = 2;
    return [test.assertEqual(3, actual), test.assertEqual(3, actual)];
})();
(function testTwo() {
    var actual = 1;
    return [test.assertEqual(3, actual), test.assertEqual(3, actual)];
})();

```

When run i see the following:

![image](https://user-images.githubusercontent.com/867568/31092859-ca331868-a77d-11e7-8171-985a656b0c84.png)

#### Tech Specs

Which Operating System are you using? MacOS Sierra

Which version of MarkLogic are you using? 9.0-2

Which version of Roxy are you using (see version.txt)? v1.7.7

**Comment by rjkennedy98** [comment]
Can we prioritize this being fixed as there is currently no alternative for unit testing with SJS.

**Comment by dmcassel** [comment]
@tternquist @rjkennedy98 I just submitted [a PR to fix this](https://github.com/marklogic-community/roxy/pull/858). Would either of you be able to check out that version and confirm that it works the way you're looking for?

**Comment by rjkennedy98** [comment]
@dmcassel Yes, I can do some verification. Thanks.

**Comment by rjkennedy98** [comment]
Its working for me. Thanks @dmcassel

**Comment by rjkennedy98** [comment]
Actually, looking more closely. There are a few weird things:
1. suiteSetup.sjs and suiteTeardown.sjs appear.
2. We only have 1 test with 1 assert. Not sure why the tests total is 2.
3. SuiteSetup.sjs is appearing twice in this list.

<testsuite errors="0" failures="0" hostname="localhost" name="edl-ml-cash-pos" tests="2" time="0.049995" timestamp="">
<testcase classname="suiteSetup.sjs" name="suiteSetup.sjs" time="0.0079992"/>
<testcase classname="get.sjs" name="get.sjs" time="0.0319968"/>
<testcase classname="suiteSetup.sjs" name="suiteSetup.sjs" time="0.0059994"/>
<testcase classname="suiteTeardown.sjs" name="suiteTeardown.sjs" time="0.0019998"/>
</testsuite>

Here is our get.sjs:

var cashPos = require("/marklogic.rest.resource/edl-ml-cash-pos/assets/resource.sjs")
var test = require('/test/test-helper.xqy');

function testHappyPath() {
var params = {
    "accountId": "0116928",
    "asOfDate": "2017-09-10",
    "positionSK": "74779212",
}
var context = {}
var response = cashPos.GET(context, params);
xdmp.log(response);
return test.assertExists(response);
}

[ testHappyPath()];

**Comment by dmcassel** [comment]
@rjkennedy98 I just pushed a commit that should fix that. Please retest.

**Comment by dmcassel** [comment]
@tternquist @rjkennedy98 ping. I think the PR fixes this bug, but it would be helpful to have a quick independent test. Either of you have a little time to do so?

**Comment by rjkennedy98** [comment]
@dmcassel  It seems to be working now. 2 things to note:
1) the Unit Test Wiki has incorrect documentation on how to do the tests
[Unit Test Wiki](https://github.com/marklogic-community/roxy/wiki/Unit-Testing#testing-server-side-javascript-with-server-side-javascript)

2) The secret sauce is doing flatten out all the assertions. 
```javascript
[].concat(testOne(), testTwo())
```

**Comment by dmcassel** [comment]
fixed in dev
