### ISSUE TITLE
Bootstrap Not Creating App Servers

### ISSUE THREAD

**Issue by xquery-guy** [marklogic-community/roxy#875]
## Thank you for submitting an issue!

If this is a bug, please use the bug template below. If this is an enhancement request, please use the RFE template below. Before submitting your issue, please do us a favor and search currently open issues. If your issue already exists, please make a comment there advocating your issue be addressed sooner.

#### The issue

Short description of the problem:
Bootstrapping does not creat appservers. Adding --apply-changes=appservers didn't do anything either.

What are the steps to reproduce the problem?
1. ./ml local bootstrap

Which Operating System are you using?
Mac OS 10.12.6
Which version of MarkLogic are you using?
9.0-4
Which version of Roxy are you using (see version.txt)?
Whatever is in the dev branch as of 3/15/18

Your business use case. How much time would this save you? Can you currently work around this missing feature?
I mean, if you can't bootstrap your appservers...

Timeframe : How urgently do you feel you need this RFE addressed? Why?
ASAP because this is a major bug.

**Comment by grtjn** [comment]
I recently heard someone else speak of this too, but I forgot who, context, and resolution. @dmcassel and @RobertSzkutak, does it ring a bell to either to you? I've not seen anything like this myself though, nor has our CI server been reporting issues.

@xquery-guy It would also help if you could elaborate if you are running a project with an ml-config.xml that contains a lot of manual edits , and if you observe this issue with a new blank Roxy project too.

**Comment by xquery-guy** [comment]
Hey Rob, Dennis here.  :) @grtjn, with my current config and codebase, using the older version of Roxy from late 2017, the app servers get created just fine via bootstrap. Using the same config and codebase with the code in your guys' dev branch (I only took in the contents of the deploy folder), if I try to bootstrap, the app servers do not get created. This is even happening locally. I'm not doing anything too fancy with the ml-config, just feeding in variables from the properties file right into the http-servers nodes in the config. Let me see if I can put together a very basic project and email it.

**Comment by heelix** [comment]
Hey guys, Chris here too.  I'm going to be tweaking the xdbc servers so we can do xccs with them.  For better or worse, we are likely going to cut over to the the dev branch.  We did find an issue with 9.0-4.2 where our server side JavaScript was impacted, so short term we are going to stick with 8.0-8.  9.x once we figure out why the SAML decryption had issues.

**Comment by xquery-guy** [comment]
I think I’ve got a simplified enough package here.
Attached is a tester roxy project. I wasn’t able to send the working Roxy code and broken Roxy code because email was blocking those files. So really all I have here is the config, props, and app_specific files. To test them, just take the roxy code from late 2017 in master and paste the files I sent under the deploy folder. Don’t worry about a src dir or whatever, we don’t need that cause we’re just testing bootstrap with app servers. Just run ./ml local bootstrap –apply-change=appservers. You should notice that the app servers get created just fine.
Now do the same thing, but use the newer code from the dev branch. The terminal will say bootstrap complete, but the appservers don’t get created. Let me know if you get the same results.
Even just doing a simple thing like changing the app port numbers on already existing app servers doesn’t work with the new Roxy code in dev.

**Comment by grtjn** [comment]
Odd. I have some pending changes for the dev branch, that have been sitting on my laptop for quite a while. I'll run a few tests in a bit, and push them into dev!

**Comment by grtjn** [comment]
@xquery-guy Can you run `./ml upgrade --branch=dev`, and try again? If you run `./ml local config` before and after, you should notice that app-servers were missing from the normalized config, and should be back in now.

**Comment by xquery-guy** [comment]
Yes, looks like it’s all working as expected now.  ☺ Can close this guy.

**Comment by grtjn** [comment]
Fixed in dev
