### ISSUE TITLE
Bootstrap fail due to ERROR: XDMP-AS: (err:XPTY0004) $field-path as xs:string -- Invalid coercion:

### ISSUE THREAD

**Issue by rajib-cts** [marklogic-community/roxy#889]
After adding one field name and path in ml-config.xml I am getting below error like 

Bootstrapping your project into MarkLogic 9 on 10.11.101.122...
WARN: Running the hybrid app-type with MarkLogic 8 is not recommended.
      Doing so requires manual patching of the Roxy rewriter.
      You will be unable to access all of the MarkLogic REST features.
      See https://github.com/marklogic/roxy/issues/416 for details.
ERROR: XDMP-AS: (err:XPTY0004) $field-path as xs:string -- Invalid coercion: (<d
b:path xmlns:db="http://marklogic.com/xdmp/database">mml:project...</db:path>, <
db:path xmlns:db="http://marklogic.com/xdmp/database">mml:project...</db:path>,
<db:path xmlns:db="http://marklogic.com/xdmp/database">mml:project...</db:path>)
 as xs:string
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED

MarkLogic Server error log

 <error:error xsi:schemaLocation="http://marklogic.com/xdmp/error error.xsd" xmlns:error="http://marklogic.com/xdmp/error" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<error:code>XDMP-AS</error:code>
<error:name>err:XPTY0004</error:name>
<error:xquery-version>1.0-ml</error:xquery-version>
<error:message>Invalid coercion</error:message>
<error:format-string>XDMP-AS: (err:XPTY0004) $field-path as xs:string -- Invalid coercion: (&lt;db:path xmlns:db="http://marklogic.com/xdmp/database"&gt;mml:project...&lt;/db:path&gt;, &lt;db:path xmlns:db="http://marklogic.com/xdmp/database"&gt;mml:project...&lt;/db:path&gt;, &lt;db:path xmlns:db="http://marklogic.com/xdmp/database"&gt;mml:project...&lt;/db:path&gt;) as xs:string</error:format-string>
<error:retryable>false</error:retryable>
<error:expr>$field-path as xs:string</error:expr>
<error:data>
  <error:datum>(&lt;db:path xmlns:db="http://marklogic.com/xdmp/database"&gt;mml:project...&lt;/db:path&gt;, &lt;db:path xmlns:db="http://marklogic.com/xdmp/database"&gt;mml:project...&lt;/db:path&gt;, &lt;db:path xmlns:db="http://marklogic.com/xdmp/database"&gt;mml:project...&lt;/db:path&gt;)</error:datum>
  <error:datum>xs:string</error:datum>
</error:data>
<error:stack>
  <error:frame>
    <error:uri>/eval</error:uri>
    <error:line>5</error:line>
    <error:column>17</error:column>
    <error:operation>setup:add-fields(&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;, xs:unsignedLong("8707683707355209358"), &lt;db:database group="Default" xmlns:db="http://marklogic.com/xdmp/database"&gt;...&lt;/db:database&gt;)</error:operation>
    <error:variables>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">database</error:name>
        <error:value>xs:unsignedLong("8707683707355209358")</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">db-config</error:name>
        <error:value>&lt;db:database group="Default" xmlns:db="http://marklogic.com/xdmp/database"&gt;...&lt;/db:database&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">field</error:name>
        <error:value>&lt;db:field xmlns:db="http://marklogic.com/xdmp/database"&gt;&lt;db:field-name&gt;...&lt;/db:field-name&gt;...&lt;/db:field&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">path</error:name>
        <error:value>&lt;db:field-path xmlns:db="http://marklogic.com/xdmp/database"&gt;&lt;db:path&gt;...&lt;/db:path&gt;...&lt;/db:field-path&gt;</error:value>
      </error:variable>
    </error:variables>
    <error:xquery-version>1.0-ml</error:xquery-version>
  </error:frame>
  <error:frame>
    <error:uri>/eval</error:uri>
    <error:line>2101</error:line>
    <error:column>23</error:column>
    <error:operation>setup:configure-indexes(&lt;configuration default-group="Default"&gt;&lt;groups xsi:schemaLocation="..." .../&gt;...&lt;/configuration&gt;)</error:operation>
    <error:variables>
      <error:variable>
        <error:name xmlns="">import-config</error:name>
        <error:value>&lt;configuration default-group="Default"&gt;&lt;groups xsi:schemaLocation="..." .../&gt;...&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">db-config</error:name>
        <error:value>&lt;db:database group="Default" xmlns:db="http://marklogic.com/xdmp/database"&gt;...&lt;/db:database&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">database-name</error:name>
        <error:value>db:database-name("mml-cms-app-content-test")</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">database</error:name>
        <error:value>xs:unsignedLong("8707683707355209358")</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration/&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">admin-config</error:name>
        <error:value>&lt;configuration&gt;&lt;databases xsi:schemaLocation="http://marklogic.com..." .../&gt;&lt;/configuration&gt;</error:value>
      </error:variable>
    </error:variables>
    <error:xquery-version>1.0-ml</error:xquery-version>
  </error:frame>
  <error:frame>
    <error:uri>/eval</error:uri>
    <error:line>704</error:line>
    <error:column>90</error:column>
    <error:operation>setup:do-setup(&lt;configuration default-group="Default"&gt;&lt;!--&amp;#10;    default-group...--&gt;...&lt;/configuration&gt;, "all,", map:map(&lt;map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../&gt;))</error:operation>
    <error:variables>
      <error:variable>
        <error:name xmlns="">import-config</error:name>
        <error:value>&lt;configuration default-group="Default"&gt;&lt;!--&amp;#10;    default-group...--&gt;...&lt;/configuration&gt;</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">options</error:name>
        <error:value>"all,"</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">properties</error:name>
        <error:value>map:map(&lt;map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../&gt;)</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">optionsMap</error:name>
        <error:value>map:map(&lt;map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../&gt;)</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">do-internals</error:name>
        <error:value>fn:false()</error:value>
      </error:variable>
      <error:variable>
        <error:name xmlns="">import-config</error:name>
        <error:value>&lt;configuration default-group="Default"&gt;&lt;groups xsi:schemaLocation="..." .../&gt;...&lt;/configuration&gt;</error:value>
      </error:variable>
    </error:variables>
    <error:xquery-version>1.0-ml</error:xquery-version>
  </error:frame>
  <error:frame>
    <error:uri>/eval</error:uri>
    <error:line>6371</error:line>
    <error:column>1</error:column>
    <error:xquery-version>1.0-ml</error:xquery-version>
  </error:frame>
</error:stack>

Which Operating System are you using?
Linux

Which version of MarkLogic are you using?
Marklogic 9.0-5
Which version of Roxy are you using (see version.txt)?
1.7.7

**Comment by grtjn** [comment]
Can you share the relevant part of your ml-config.xml?

**Comment by rajib-cts** [comment]
<fields>
        <field>
          <field-name>suggest-field-project</field-name>
          <field-path>
            <path>mml:project/mml:feed/mml:title</path>
            <weight>1.0</weight>
            <path>mml:project/mml:feed/mml:author</path>
            <weight>1.0</weight>	
            <path>mml:project/mml:feed/mml:isbn</path>
            <weight>1.0</weight>
       </field-path>
          <word-lexicons/>
          <included-elements/>
          <excluded-elements/>
          <tokenizer-overrides/>
          <stemmed-searches>basic</stemmed-searches>
          <fast-phrase-searches>true</fast-phrase-searches>
          <fast-case-sensitive-searches>true</fast-case-sensitive-searches>
          <fast-diacritic-sensitive-searches>true</fast-diacritic-sensitive-searches>
        </field>
        <field>
          <field-name>suggest-field-content</field-name>
          <field-path>
            <path>mml:content/mml:feed/mml:descriptive/mml:title</path>
            <weight>1.0</weight>
            <path>mml:content/mml:feed/mml:contentType</path>
            <weight>1.0</weight>	
	</field-path>
          <word-lexicons/>
          <included-elements/>
          <excluded-elements/>
          <tokenizer-overrides/>
          <stemmed-searches>basic</stemmed-searches>
          <fast-phrase-searches>true</fast-phrase-searches>
          <fast-case-sensitive-searches>true</fast-case-sensitive-searches>
          <fast-diacritic-sensitive-searches>true</fast-diacritic-sensitive-searches>
        </field>
        <field>
          <field-name>suggest-field-all</field-name>
          <field-path>
            <path>mml:project/mml:feed/mml:title</path>
            <weight>1.0</weight>
            <path>mml:project/mml:feed/mml:author</path>
            <weight>1.0</weight>	
            <path>mml:project/mml:feed/mml:isbn</path>
            <weight>1.0</weight>		  
            <path>mml:content/mml:feed/mml:descriptive/mml:title</path>
            <weight>1.0</weight>
            <path>mml:content/mml:feed/mml:contentType</path>
            <weight>1.0</weight>	
		 </field-path>
          <word-lexicons/>
          <included-elements/>
          <excluded-elements/>
          <tokenizer-overrides/>
          <stemmed-searches>basic</stemmed-searches>
          <fast-phrase-searches>true</fast-phrase-searches>
          <fast-case-sensitive-searches>true</fast-case-sensitive-searches>
          <fast-diacritic-sensitive-searches>true</fast-diacritic-sensitive-searches>
        </field>
        <field>
          <field-name/>
          <include-root>true</include-root>
          <fast-case-sensitive-searches>false</fast-case-sensitive-searches>
          <fast-diacritic-sensitive-searches>false</fast-diacritic-sensitive-searches>
          <fast-phrase-searches>false</fast-phrase-searches>
          <one-character-searches>false</one-character-searches>
          <stemmed-searches>basic</stemmed-searches>
          <three-character-searches>false</three-character-searches>
          <three-character-word-positions>false</three-character-word-positions>
          <trailing-wildcard-searches>false</trailing-wildcard-searches>
          <trailing-wildcard-word-positions>false</trailing-wildcard-word-positions>
          <two-character-searches>false</two-character-searches>
          <value-positions>false</value-positions>
          <value-searches>false</value-searches>
          <word-searches>false</word-searches>
          <word-lexicons/>
          <included-elements>
            <included-element>
              <namespace-uri>http://ns.com</namespace-uri>
              <localname>blah</localname>
              <weight>1.0</weight>
              <attribute-namespace-uri/>
              <attribute-localname/>
              <attribute-value/>
            </included-element>
          </included-elements>
          <excluded-elements/>
        </field>
      </fields>

     <range-element-indexes>


        <range-field-index>
          <scalar-type>string</scalar-type>
          <field-name>suggest-field-project</field-name>
          <collation>http://marklogic.com/collation/</collation>
          <range-value-positions>false</range-value-positions>
	  <invalid-values>ignore</invalid-values>
        </range-field-index>
        <range-field-index>
          <scalar-type>string</scalar-type>
          <field-name>suggest-field-content</field-name>
          <collation>http://marklogic.com/collation/</collation>
          <range-value-positions>false</range-value-positions>
	 <invalid-values>ignore</invalid-values>
        </range-field-index>	
        <range-field-index>
          <scalar-type>string</scalar-type>
          <field-name>suggest-field-all</field-name>
          <collation>http://marklogic.com/collation/</collation>
          <range-value-positions>false</range-value-positions>
	  <invalid-values>ignore</invalid-values>
        </range-field-index>

**Comment by grtjn** [comment]
You have to wrap each combination of a path and weight element into separate field-path element, and not group them all together in one..

**Comment by rajib-cts** [comment]
Thanks @grtjn, Its working fine now.
