### ISSUE TITLE
shared properties not prefixed with 'ml.`

### ISSUE THREAD

**Issue by kefo** [marklogic-community/roxy#892]
When shared properties are loaded, they are not prefixed with `ml.`.  As such, they do not overwrite previously defined properties, nor are they used.

Compare: 
https://github.com/marklogic-community/roxy/blob/master/deploy/lib/server_config.rb#L3173

With:
https://github.com/marklogic-community/roxy/blob/master/deploy/lib/server_config.rb#L3178

Pull request imminent.

**Comment by grtjn** [comment]
Merged in dev
